/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfiguracionModoJuego.java
 *
 * Created on 24/07/2009, 06:43:08 PM
 */

package tanques;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class ConfiguracionModoJuego extends javax.swing.JFrame
{

    /** Creates new form ConfiguracionModoJuego */
    public ConfiguracionModoJuego() {
        initComponents();
        this.setLocation((util.tamañoPantalla.width-this.getWidth())/2, (util.tamañoPantalla.height-this.getHeight())/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modoDeJuedo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidaModoJuego = new javax.swing.JTextField();
        okModoJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        modoDeJuedo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A Muerte", "A Tiempo", "A Golpes" }));
        modoDeJuedo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modoDeJuedoKeyPressed(evt);
            }
        });

        jLabel1.setText("Modo de Juego:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Configuracion Del Juego");

        jLabel3.setText("Cantidad (Muertes, Minutos, Golpes)");

        cantidaModoJuego.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidaModoJuego.setText("5");
        cantidaModoJuego.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidaModoJuegoKeyPressed(evt);
            }
        });

        okModoJuego.setText("Listo");
        okModoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okModoJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okModoJuego, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(modoDeJuedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cantidaModoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modoDeJuedo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidaModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okModoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okModoJuegoActionPerformed
        try
        {
        switch(modoDeJuedo.getSelectedIndex())
        {
            case 0:
                if(Integer.parseInt(cantidaModoJuego.getText()) > 0 && Integer.parseInt(cantidaModoJuego.getText()) <= 99)
                {
                    util.estado = Pantalla.MULTIJUEGO;
                    util.modo = util.MUERTES;
                    util.cantidadMuertes = Integer.parseInt(cantidaModoJuego.getText());
                    util.mostrandoConfiguracion = false;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "¡Error: Cantidad ingresada incorrecta, minimo 1 y maximo 99!");
                }
                break;
            case 1:
                if(Integer.parseInt(cantidaModoJuego.getText()) > 0 && Integer.parseInt(cantidaModoJuego.getText()) <= 99)
                {
                    util.estado = Pantalla.MULTIJUEGO;
                    util.modo = util.TIEMPO;
                    util.cantidadMinutos = Integer.parseInt(cantidaModoJuego.getText());
                    util.mostrandoConfiguracion = false;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "¡Error: Cantidad ingresada incorrecta, minimo 1 y maximo 99!");
                }
                break;
            case 2:
                if(Integer.parseInt(cantidaModoJuego.getText()) > 0 && Integer.parseInt(cantidaModoJuego.getText()) <= 1000)
                {
                    util.estado = Pantalla.MULTIJUEGO;
                    util.modo = util.GOLPES;
                    util.cantidadGolpes = Integer.parseInt(cantidaModoJuego.getText());
                    util.mostrandoConfiguracion = false;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "¡Error: Cantidad ingresada incorrecta, minimo 1 y maximo 1000!");
                }
                break;
        }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "¡Error: Solo se pueden ingresar numeros!");
        }
}//GEN-LAST:event_okModoJuegoActionPerformed

    private void cantidaModoJuegoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidaModoJuegoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){okModoJuegoActionPerformed(null);}
    }//GEN-LAST:event_cantidaModoJuegoKeyPressed

    private void modoDeJuedoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modoDeJuedoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){okModoJuegoActionPerformed(null);}
    }//GEN-LAST:event_modoDeJuedoKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionModoJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidaModoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox modoDeJuedo;
    private javax.swing.JButton okModoJuego;
    // End of variables declaration//GEN-END:variables
}
